import React from "react";

export const dummy = [
  {
    PROJECT_NAME: "Allosaurus web app",
    STATUS: "on track",
    PM: { name: "Maria Garcia", image: "https://unsplash.it/150/200?human" },
    LAST_UPDATE: "15 Mar 2021, 12:47 PM",
    RESOURCES: 3,
    PROJECT_TIMELINE: "15 May 2021 > 15 Aug 2021",
    ESTIMATION: "US$ 10.5K",
  },
  {
    PROJECT_NAME: "MicroRaptor website",
    STATUS: "on track",
    PM: { name: "Li Wang", image: "https://unsplash.it/150/200?human2" },
    LAST_UPDATE: "15 Mar 2021, 12:47 PM",
    RESOURCES: 3,
    PROJECT_TIMELINE: "15 May 2021 > 15 Aug 2021",
    ESTIMATION: "US$ 10.5K",
  },
  {
    PROJECT_NAME: "Tarius landing page",
    STATUS: "On Hold",
    PM: { name: "Li Wang", image: "https://unsplash.it/150/200?human3" },
    LAST_UPDATE: "15 Mar 2021, 12:47 PM",
    RESOURCES: null,
    PROJECT_TIMELINE: "15 May 2021 > 15 Aug 2021",
    ESTIMATION: "US$ 10.5K",
  },
  {
    PROJECT_NAME: "Rugops App",
    STATUS: "At risk",
    PM: "Sarah Jones",
    LAST_UPDATE: "15 Mar 2021, 12:47 PM",
    RESOURCES: 3,
    PROJECT_TIMELINE: "15 May 2021 > 15 Aug 2021",
    ESTIMATION: "US$ 10.5K",
  },
  {
    PROJECT_NAME: "Erketu",
    STATUS: "On track",
    PM: "John Smith",
    LAST_UPDATE: "15 Mar 2021, 12:47 PM",
    RESOURCES: 3,
    PROJECT_TIMELINE: "15 May 2021 > 15 Aug 2021",
    ESTIMATION: "US$ 10.5K",
  },
  {
    PROJECT_NAME: "Capricorn",
    STATUS: "On track",
    PM: { name: "Li Wang", image: "https://unsplash.it/150/200?human4" },
    LAST_UPDATE: "15 Mar 2021, 12:47 PM",
    RESOURCES: 3,
    PROJECT_TIMELINE: "15 May 2021 > 15 Aug 2021",
    ESTIMATION: "US$ 10.5K",
  },
  {
    PROJECT_NAME: "Sagittarius",
    STATUS: "Potential risk",
    PM: "Maria Garcia",
    LAST_UPDATE: "15 Mar 2021, 12:47 PM",
    RESOURCES: 3,
    PROJECT_TIMELINE: "15 May 2021 > 15 Aug 2021",
    ESTIMATION: "US$ 10.5K",
  },
  {
    PROJECT_NAME: "Gemini",
    STATUS: "on track",
    PM: "Sarah Jones",
    LAST_UPDATE: "15 Mar 2021, 12:47 PM",
    RESOURCES: 3,
    PROJECT_TIMELINE: "15 May 2021 > 15 Aug 2021",
    ESTIMATION: "US$ 10.5K",
  },
  {
    PROJECT_NAME: "Pisces",
    STATUS: "On track",
    PM: "John Smith",
    LAST_UPDATE: "15 Mar 2021, 12:47 PM",
    RESOURCES: 3,
    PROJECT_TIMELINE: "15 May 2021 > 15 Aug 2021",
    ESTIMATION: "US$ 10.5K",
  },
  {
    PROJECT_NAME: "Taurus",
    STATUS: "On track",
    PM: { name: "Li Wang", image: "https://unsplash.it/150/200?image" },
    LAST_UPDATE: "15 Mar 2021, 12:47 PM",
    RESOURCES: 3,
    PROJECT_TIMELINE: "15 May 2021 > 15 Aug 2021",
    ESTIMATION: "US$ 10.5K",
  },
  {
    PROJECT_NAME: "Osiris",
    STATUS: "At risk",
    PM: { name: "Li Wang", image: "https://unsplash.it/150/200?image" },
    LAST_UPDATE: "15 Mar 2021, 12:47 PM",
    RESOURCES: 3,
    PROJECT_TIMELINE: "15 May 2021 > 15 Aug 2021",
    ESTIMATION: "US$ 10.5K",
  },
  {
    PROJECT_NAME: "Horus",
    STATUS: "On track",
    LAST_UPDATE: "15 Mar 2021, 12:47 PM",
    RESOURCES: 3,
    PROJECT_TIMELINE: "15 May 2021 > 15 Aug 2021",
    ESTIMATION: "US$ 10.5K",
  },
  {
    PROJECT_NAME: "Hathor",
    STATUS: "On track",
    LAST_UPDATE: "15 Mar 2021, 12:47 PM",
    RESOURCES: 3,
    PROJECT_TIMELINE: "15 May 2021 > 15 Aug 2021",
    ESTIMATION: "US$ 10.5K",
  },
  {
    PROJECT_NAME: "Anubis",
    STATUS: "on track",
    LAST_UPDATE: "15 Mar 2021, 12:47 PM",
    RESOURCES: 3,
    PROJECT_TIMELINE: "15 May 2021 > 15 Aug 2021",
    ESTIMATION: "US$ 10.5K",
  },
  {
    PROJECT_NAME: "Othello",
    STATUS: "On track",
    LAST_UPDATE: "15 Mar 2021, 12:47 PM",
    RESOURCES: 3,
    PROJECT_TIMELINE: "15 May 2021 > 15 Aug 2021",
    ESTIMATION: "US$ 10.5K",
  },
  {
    PROJECT_NAME: "Ophelia",
    STATUS: "On track",
    LAST_UPDATE: "15 Mar 2021, 12:47 PM",
    RESOURCES: 3,
    PROJECT_TIMELINE: "15 May 2021 > 15 Aug 2021",
    ESTIMATION: "US$ 10.5K",
  },
  {
    PROJECT_NAME: "Arcand",
    STATUS: "On track",
    LAST_UPDATE: "15 Mar 2021, 12:47 PM",
    RESOURCES: 3,
    PROJECT_TIMELINE: "15 May 2021 > 15 Aug 2021",
    ESTIMATION: "US$ 10.5K",
  },
  {
    PROJECT_NAME: "Madsen",
    STATUS: "on hold",
    LAST_UPDATE: "15 Mar 2021, 12:47 PM",
    RESOURCES: 3,
    PROJECT_TIMELINE: "15 May 2021 > 15 Aug 2021",
    ESTIMATION: "US$ 10.5K",
  },
  {
    PROJECT_NAME: "Schleifer",
    STATUS: "On track",
    LAST_UPDATE: "15 Mar 2021, 12:47 PM",
    RESOURCES: 3,
    PROJECT_TIMELINE: "15 May 2021 > 15 Aug 2021",
    ESTIMATION: "US$ 10.5K",
  },
  {
    PROJECT_NAME: "siphron",
    STATUS: "On hold",
    LAST_UPDATE: "15 Mar 2021, 12:47 PM",
    RESOURCES: 3,
    PROJECT_TIMELINE: "15 May 2021 > 15 Aug 2021",
    ESTIMATION: "US$ 10.5K",
  },
];

export const TableHead = [
  {
    id: 1,
    name: "All",
    key: "all",
    value: dummy?.length,
  },
  {
    id: 2,
    name: "Risk",
    key: "at risk",
    value: dummy?.filter((val) => val.STATUS.toLowerCase() === "at risk")
      .length,
  },
  {
    id: 3,
    name: "onHold",
    key: "on hold",
    value: dummy?.filter((val) => val.STATUS.toLowerCase() === "on hold")
      .length,
  },
  {
    id: 4,
    name: "potential risk",
    key: "potential risk",
    value: dummy?.filter((val) => val.STATUS.toLowerCase() === "potential risk")
      .length,
  },
  {
    id: 5,
    name: "on track",
    key: "on track",
    value: dummy?.filter((val) => val.STATUS.toLowerCase() === "on track")
      .length,
  },
];
